services:
  - type: web
    name: GeneralMathsMOD
    env: static
    plan: Starter
    region: Frankfurt
    buildCommand: bash render.sh
    staticPublishPath: ./static
    pullRequestPreviewsEnabled: true
